/// <reference types="jquery" />
/// <reference types="tooltipster" />
import { NPCPF2e } from "@actor/index";
import { ActorSheetPF2e } from "@actor/sheet/base";
import { ActorDataPF2e } from "@actor/data";
export declare class ActorSheetPF2eDataEntryNPC extends ActorSheetPF2e<NPCPF2e> {
    private readonly CUSTOM_TRAIT_SEPARATOR;
    private readonly CREATURE_TRAITS;
    static get defaultOptions(): ActorSheetOptions & {
        classes: string[];
        submitOnClose: boolean;
        scrollY: string[];
    } & {
        classes: string[];
    };
    get template(): string;
    protected prepareItems(_sheetData: { actor: ActorDataPF2e }): void;
    getData(): {
        app: {
            id: `actor-${string}` | `actor-${string}-${string}`;
        };
        dataset: {
            alignment: {
                LG: string;
                NG: string;
                CG: string;
                LN: string;
                N: string;
                CN: string;
                LE: string;
                NE: string;
                CE: string;
            };
            rarity: {
                common: string;
                uncommon: string;
                rare: string;
                unique: string;
            };
            size: {
                tiny: string;
                sm: string;
                med: string;
                lg: string;
                huge: string;
                grg: string;
            };
            traits: {
                creature: {
                    aberration: string;
                    acid: string;
                    aeon: string;
                    aesir: string;
                    agathion: string;
                    air: string;
                    alchemical: string;
                    amphibious: string;
                    anadi: string;
                    angel: string;
                    animal: string;
                    aquatic: string;
                    archon: string;
                    astral: string;
                    asura: string;
                    azata: string;
                    beast: string;
                    boggard: string;
                    caligni: string;
                    celestial: string;
                    "charau-ka": string;
                    clockwork: string;
                    cold: string;
                    couatl: string;
                    construct: string;
                    daemon: string;
                    demon: string;
                    dero: string;
                    devil: string;
                    dhampir: string;
                    div: string;
                    dinosaur: string;
                    dragon: string;
                    dream: string;
                    drow: string;
                    duergar: string;
                    duskwalker: string;
                    earth: string;
                    elemental: string;
                    ethereal: string;
                    fetchling: string;
                    fey: string;
                    fiend: string;
                    fungus: string;
                    genie: string;
                    ghoran: string;
                    ghost: string;
                    ghoul: string;
                    giant: string;
                    gnoll: string;
                    golem: string;
                    gremlin: string;
                    grioth: string;
                    grippli: string;
                    hag: string;
                    herald: string;
                    humanoid: string;
                    ifrit: string;
                    incorporeal: string;
                    inevitable: string;
                    kami: string;
                    kobold: string;
                    kovintus: string;
                    locathah: string;
                    merfolk: string;
                    mindless: string;
                    minion: string;
                    monitor: string;
                    mortic: string;
                    mummy: string;
                    munavri: string;
                    mutant: string;
                    nagaji: string;
                    nymph: string;
                    oni: string;
                    ooze: string;
                    orc: string;
                    oread: string;
                    paaridar: string;
                    petitioner: string;
                    phanton: string;
                    plant: string;
                    protean: string;
                    psychopomp: string;
                    qlippoth: string;
                    rakshasa: string;
                    ratfolk: string;
                    sahkil: string;
                    samsaran: string;
                    "sea devil": string;
                    serpentfolk: string;
                    shabti: string;
                    shadow: string;
                    siktempora: string;
                    skeleton: string;
                    skelm: string;
                    skulk: string;
                    soulbound: string;
                    spirit: string;
                    spriggan: string;
                    sprite: string;
                    stheno: string;
                    suli: string;
                    swarm: string;
                    sylph: string;
                    tane: string;
                    tanggal: string;
                    tengu: string;
                    time: string;
                    titan: string;
                    troll: string;
                    undead: string;
                    undine: string;
                    urdefhan: string;
                    vampire: string;
                    vanara: string;
                    velstrac: string;
                    vishkanya: string;
                    water: string;
                    wayang: string;
                    werecreature: string;
                    wight: string;
                    wraith: string;
                    wyrwood: string;
                    xulgath: string;
                    zombie: string;
                    aasimar: string;
                    android: string;
                    aphorite: string;
                    azarketi: string;
                    beastkin: string;
                    catfolk: string;
                    changeling: string;
                    conrasu: string;
                    dwarf: string;
                    elf: string;
                    fleshwarp: string;
                    ganzi: string;
                    geniekin: string;
                    gnome: string;
                    goblin: string;
                    "half-elf": string;
                    halfling: string;
                    "half-orc": string;
                    human: string;
                    hobgoblin: string;
                    kitsune: string;
                    leshy: string;
                    lizardfolk: string;
                    shoony: string;
                    strix: string;
                    tiefling: string;
                };
            };
        };
        isTargetFlatFooted: boolean;
        isProficiencyLocked: boolean;
        user: {
            isGM: boolean;
        };
        totalCoinage: import("../sheet/data-types").CoinageSummary;
        totalCoinageGold: string;
        totalWealth: import("../../item/treasure/helpers").Coins;
        totalWealthGold: string;
        actor: any;
        data: any;
        items: any;
        cssClass: "locked" | "editable";
        effects: RawObject<
            foundry.data.ActiveEffectData<import("../../active-effect").ActiveEffectPF2e>
        >[];
        limited: boolean;
        options: ActorSheetOptions;
        editable: boolean;
        document: NPCPF2e;
        owner: boolean;
        title: string;
    };
    activateListeners(html: JQuery): void;
    protected _render(force?: boolean, options?: RenderOptions): Promise<void>;
}
